baseURL: https://oscareduardolp6.github.io/
languageCode: es-mx
title: Oscar López 
theme: hugo-profile 

Paginate: 3
disqusShortname: oscarlp6

markup: 
  goldmark: 
    renderer: 
      unsafe: true 

Menus: 
  main: 
    - identifier: about
      name: Sobre mí
      title: Sobre mí 
      url: /#about
      wight: 1
    - identifier: experience
      name: Experiencia
      title: Experiencia
      url: /#experience
      wight: 1
    - identifier: education
      name: Educación
      title: Educación
      url: /#education
      wight: 1
    # - identifier: achievements
    #   name: Logros
    #   title: Logros
    #   url: /#achievements
    #   wight: 1
    - identifier: contact
      name: Contacto
      title: Contacto
      url: /#contact
      wight: 1
    - identifier: projects
      name: Proyectos
      title: Proyectos
      url: /#projects
      wight: 1
    # - identifier: blog 
    #   name: Blog
    #   title: Blog posts 
    #   url: /blogs
    #   weight: 1 
      
defaultContentLanguage: es

languages: 
  en: 
    languageName: English
    weight: 2 
    description: Oscar Lopez Portfolio
    Menus: 
      main: 
        - identifier: about 
          name: About me 
          title: About me 
          url: /en/#about
          wight: 1
        - identifier: experience 
          name: Experience 
          title: Experience 
          url: /en/#experience
          wight: 2
        - identifier: education 
          name: Education 
          title: Education 
          url: /en/#experience
          wight: 3
        - identifier: contact 
          name: Contact 
          title: Contact 
          url: /en/#contact
          wight: 4
        - identifier: projects 
          name: Projects 
          title: Projects 
          url: /en/#projects
          wight: 5
    hero: 
      enable: true
      intro: "Hi, I'm"
      title: "Oscar Lopez"
      subtitle: "Fullstack web developer"
      content: "I'm dedicated to create solutions that generate value to the user.
      Specialized in **web development**, I've worked on *corporative* , *industrial* & 
      *back office* solutions.
      A passionate of continuos learning, expand my social circle & interact with people. "
      image: /profile.jpg
      button:
        enable: true
        name: "Resume"
        url: "/docs/Resume.pdf"
        download: true 
      socialLinks: 
        fontAwesomeIcons: 
          - icon: fab fa-github
            url: https://github.com/oscareduardolp6
          - icon: fab fa-linkedin
            url: https://www.linkedin.com/in/oscareduardolp6/
    about: 
      enable: true
      title: "About me"
      image: "/images/me.jpg"
      content: |-
        Born in *Naucalpan, Estado de México*, for a time I resided in *Monterrey, Nuevo Léon* and the last **nine years** I've lived in *León, Guanajuato*. 

        Since a Young age my parents teach me an interes for knowing the details of how the things work, both computers & and people, leading me to some of my passions, *software development* and *ilusionism*, the last giving me an excuse to connect with people and a way to share emotions. 

        My **professional goal** es create scalable and high quality software with techs that exites me and teach me. 
      skills: 
        enable: true 
        title: "Technologies"
        items: 
          - "CSS / Sass"
          - "React (With Typescript)"
          - "Angular / AngularJS"
          - ".NET with C# & VB"
          - "Node / Deno / Bun"
          - "Python"
          - "SQL / Transact-SQL"
          - "Go"
    experience: 
      enable: true 
      items: 
        - job: "Web Developer"
          company: "Educafin"
          date: "March 2020 - December 2021"
          info: 
            enable: false 
          featuredLink: 
            enable: false 
          content: |-
            Part of the **SOS Inspira** platform development team, designed 
            to manage the mentoring program. 

            Build with `PHP` & `CodeIgniter`, `MariaDB` as *Database* And `Vue` 
            on the *Frontend*. 

            I was also involved in the initial development of the platform 
            **JuventudesGTO**, designed for the research area. 
        - job: "Software Project Developer"
          company: "Proservicio"
          companyUrl: "https://www.serviacero.com/proservicio"
          date: "October 2020 - March 2022"
          featuredLink: 
            enable: false
          info: 
            enable: false 
          content: |- 
            Part of the **Software Project Development Team**. 
            A company focused in generate software to both *web* and *custom 
            modules* for the *ERP*, specifically designed for each specialitie 
            of the [Serviacero Group](https://serviacero.com/). 

            I worked in the development of the *Carta Porte(SAT)* project. 

            **Technologies** 
            - .NET 
            - React With Typescript 
            - Progress 4GL 
            - SQL  

        - job: ".Net & Winforms Developer"
          company: "IROX IT"
          companyUrl: "http://iroxit.com/"
          date: "March 2022 - August 2022"
          info: 
            enable: false 
          featuredLink: 
            enable: false 
          content: |- 
            Developer in the *Supplier Assistance team*. 

            Centered on  developing modules for the internal management
            application of providers. 

            Made with *frontend* in *Winforms* and *backend* in *.Net Services*. 
        - job: ".NET & Web Developer"
          company: "IROX IT"
          companyUrl: "http://iroxit.com/"
          date: "August 2022 - Present"
          info:
            enable: false 
          featuredLink: 
            enable: false 
          content: |- 
            Currently part of the **Damage** team at **[HDI Seguros](https://www.hdi.com.mx/)** as 
            developer from the consulting firm [IROX IT](http://iroxit.com/). 

            I develop modules & functionalities for the *internal web application of 
            quoting and issuance policies*. 

            *Microservices* in `.NET` and *frontend* in `Angular`. 
    education: 
      enable: true 
      title: Education 
      items: 
        - title: "Software Engineer"
          school:
            name: "Instituto Tecnológico de León"
            url: "https://leon.tecnm.mx/"
          date: "2017 - 2022"
          content: |- 
            **Extracurricular activities** 
            - *Punto Azul* (Sales Software developed by [Aldo López](https://www.linkedin.com/in/aldo-l%C3%B3pez-868b10221/) & **Andrés Sierra**) Tester. 
            - 1° Place team in my institution in the **Cundinamarca University Hackathon** .
            - Proposal for redesign of the University Students Site. 
    achievements: 
      enable: false 
      items: 
        - title: Go from scratch 
          content: Go Basic Course Completion Certificate
          url: /docs/Certifications/CertificadoGolang.png
        - title: Programming Exercises 
          content: Programming Exercises in LeetCode 
          url: https://leetcode.com/oscareduardolp6/  
    projects: 
      enable: true 
      items: 
        - title: "Sales & Inventory Manager for JM Mueblería"
          content: "Tool to manage the control of the store, allowing to have the stock 
          information centralized in a server to be consumed from several client 
          computers. 
          Server developed in `Deno` with *Typescript*,  UI with `React` & `Electron`"
          image: /images/projects/Muebleria-1.png
          badges: 
            - "Deno"
            - "Typescript"
            - "React"
            - "Electron"
          links: 
            - icon: fab fa-facebook
              url: https://www.facebook.com/JMuebleria
              tooltip: JM Mueblería
            - icon: fab fa-github
              url: https://github.com/oscareduardolp6/muebleria
              tooltip: Frontend
            - icon: fab fa-github
              url: https://github.com/oscareduardolp6/Share
              tooltip: Share Code 
            - icon: fab fa-github 
              url: https://github.com/oscareduardolp6/Owl_Sales_Point_Back 
              tooltip: Backend 
        - title: "Memory Trainer"
          content: "Project made to improve my memory, the idea is remember certain 
          number of words in order, after, you have to repeat all words in the same 
          order. 
          The program will tell you if your word & order is correct or not. 
          In order to facilitate  the result, the software ask if you think 
          that you can remember or if you want to change it"
          image: /images/projects/memory-trainer-1.png
          featured: 
            name: Demo 
            link: /projects/memory-trainer 
          badges: 
            - "React"
            - "CSS"
          links: 
            - icon: fab fa-github
              url: https://github.com/gurusabarish/converter
              tooltip: React Code
    contact:
      enable: true 
      content: Get in Touch 
      email: oscareduardolp6@gmail.com
      btnName: Email
      whatsapp: 524773010668
    footer: 
      recentPosts: false 
      socialNetworks:
        github: https://github.com/oscareduardolp6
        linkedin: https://www.linkedin.com/in/oscareduardolp6/
        # twitter: https://twitter.com
        instagram: https://www.instagram.com/oscar_lp6/
        # facebook: https://facebook.comg

  es: 
    languageName: Spanish 
    weight: 1
    hero: 
      enable: true
      intro: "Hola, soy"
      title: "Oscar López"
      subtitle: "Desarrollador web fullstack"
      content: "Me dedico a crear soluciones que agreguen valor al usuario. 
      Especializado en **desarrollo web**, he trabajado, principalmente, en soluciones *corporativas*, *industriales* 
      y de *back office*. 
      Soy un apasionado del aprendizaje continuo y ampliar mi circulo social. " 
      image: /profile.jpg
      button:
        enable: true
        name: "CV"
        url: "/docs/CV.pdf"
        download: true 
      socialLinks: 
        fontAwesomeIcons: 
          - icon: fab fa-github
            url: https://github.com/oscareduardolp6
          - icon: fab fa-linkedin
            url: https://www.linkedin.com/in/oscareduardolp6/
    about: 
      enable: true
      title: "Sobre mí"
      image: "/images/me.jpg"
      content: |- 
        Originario de *Naucalpan, Estado de México*, viví un tiempo en 
        *Monterrey, Nuevo León* y desde hace **catorce años** vivo en *León, Guanajuato*. 

        Desde jovén mis padres me inculcaron el interés por saber los detalles de 
        cómo funcionan las cosas, desde las *computadoras* hasta las 
        *mentes de las personas*, llevandome a mis pasiones, 
        el *desarrollo de software* y el *ilusionismo*, este último dandome una 
        excusa para conectar con las personas y transmitir emociones.

        Mi **objetivo profesional** es crear software escalable y de calidad en 
        tecnologías *modernas* que me divertan y enseñen.

      skills: 
        enable: true 
        title: "Técnologías"
        items: 
          - "CSS / Sass"
          - "React (Con Typescript)"
          - "Angular / AngularJS"
          - ".NET con C# & VB"
          - "Node / Deno / Bun"
          - "Python"
          - "SQL / Transact-SQL"
          - "Go"
          - "Electron"
          - "Next.js"
          # - "Typescript / Javascript"
    experience: 
      enable: true 
      title: Experiencia
      items: 
        - job: "Desarrollador Web"
          company: "Educafin"
          date: "Marzo 2020 - Diciembre 2021"
          info: 
            enable: false 
          featuredLink: 
            enable: false 
          content: |-
            Parte del equipo de desarrollo de la plataforma **SOS Inspira**, 
            pensada para llevar el control del programa de mentores
            y mentorados de la institución, construido en `PHP` con `Code Igniter`, 
            `MariaDB` para base de datos y `Vue` en el 
            *frontend*. 

            También estuve involucrado en el desarrollo inicial de la plataforma 
            **JuventudesGTO**, pensada para el área de
            investigación .
        - job: "Desarrollador de proyectos de Software" 
          company: "Proservicio"
          companyUrl: "https://www.serviacero.com/proservicio"
          date: "Octubre 2020 - Marzo 2022"
          featuredLink:
            enable: false
          info: 
            enable: false 
          content: |- 
            Fui parte del equipo de desarrollo de proyectos, la empresa enfocada
            en generar software tanto *web*, como módulos para el *ERP* personalizados 
            diseñados a la medida para cada una de las especialidades del [[Grupo Serviacero]](https://serviacero.com/). 

            Participé en el desarrollo de integración del sistema de emision de *Carta Porte*. 

            **Tecnologías** 
            - .Net 
            - React con Typescript 
            - Progress 4GL 
            - SQL 
        - job: "Desarrollador .NET & Winforms"
          company: "IROX IT"
          companyUrl: "http://iroxit.com/"
          date: "Marzo 2022 - Agosto 2022"
          info: 
            enable: false 
          featuredLink: 
            enable: false 
          content: |- 
            Desarrollador en el equipo de *Asistencia a proveedores* 
            para **[HDI Seguros](https://www.hdi.com.mx/)**.

            Enfocado a desarrollar módulos para el aplicativo interno de gestión 
            a proveedores, manejando  el *frontend* con `Winforms` y el *backend* 
            con servicios desarrollados en `.NET`. 
        - job: "Desarrollador .NET y Web"
          company: "IROX IT"
          companyUrl: "http://iroxit.com/"
          date: "Agosto 2022 - Presente"
          info: 
            enable: false 
          featuredLink: 
            enable: false 
          content: |-
            Actualmente soy parte del equipo de **Daños** de **[HDI Seguros](https://www.hdi.com.mx/)**
            desde la consultora [IROX IT](http://iroxit.com/). 

            Participo desarrollando módulos y funcionalidades para la aplicación web interna de 
            cotización y emisión de polizas, *microservicios* en `.NET` y *frontend* en `Angular`. 
    education: 
      enable: true 
      title: Educación 
      items: 
        - title: "Ingeniería en sistemas computacionales"
          school: 
            name: "Instituto Tecnológico de León"
            url: "https://leon.tecnm.mx/"
          date: "2017 - 2022"
          content: |- 
            **Actividades Extracurriculares** 
            - Tester de **Punto Azul** Software de ventas desarrollado por 
            *[Aldo López](https://www.linkedin.com/in/aldo-l%C3%B3pez-868b10221/)* 
            y *Andrés Sierra*. 
            - Equipo 1° Lugar dentro del instituto en el **Hackaton de la Universidad 
            Cundinamarca** . 
            - Propuesta para rediseño del sitio estudiantil de la *institución*. 
    achievements: 
      title: "Logros"
      enable: false 
      items:
        - title: Go desde cero 
          content: Certificado de terminación del Curso básico de Go
          url: /docs/Certifications/CertificadoGolang.png
        - title: Mis ejercicios de programación 
          content: Ejercicios de programación en LeetCode 
          url: https://leetcode.com/oscareduardolp6/  
    projects: 
      title: "Proyectos"
      enable: true
      items: 
        - title: "Manejador de Inventario y ventas para JM Mublería"
          content: "Herramienta hecha para el control de la tienda física, 
          permitiendo tener la información del almacén centralizada para ser 
          consumida desde varias computadora cliente, desarrollada con un 
          *servidor* `Deno` en *Typescript* y la *UI* con `React` y `Electron`"
          image: /images/projects/Muebleria-1.png
          badges: 
            - "Deno"
            - "Typescript"
            - "React"
            - "Electron"
          links: 
            - icon: fab fa-facebook
              url: https://www.facebook.com/JMuebleria
              tooltip: JM Mueblería
            - icon: fab fa-github
              url: https://github.com/oscareduardolp6/muebleria
              tooltip: Frontend
            - icon: fab fa-github
              url: https://github.com/oscareduardolp6/Share
              tooltip: Share Code 
            - icon: fab fa-github 
              url: https://github.com/oscareduardolp6/Owl_Sales_Point_Back 
              tooltip: Backend 
        - title: "Entrenador de memoria"
          content: "Proyecto hecho para mejorar mi memoria, la idea es recordar cierto
          numero de palabras en orden, para después repetirlas en el mismo orden. 
          El programa nos dirá si lo hemos hecho correctamente o si hemos fallado,
          para mejorar el resultado, se nos pregunta si creemos que podemos recordar 
          la palabra o si por no conocerla o su complejidad, queremos cambiarla"
          image: /images/projects/memory-trainer-1.png
          featured: 
            name: Demo 
            link: /projects/memory-trainer
          badges: 
            - "React"
            - "CSS"
          links: 
            - icon: fab fa-github
              url: https://github.com/gurusabarish/converter
              tooltip: React Code
    contact: 
      title: Contacto
      enable: true 
      content: No dudes en contactarme :) 
      email: oscareduardolp6@gmail.com
      btnName: Email
      whatsapp: 524773010668
    footer: 
      recentPosts: false 
      recentPostTitle: Entradas Recientes
      socialNetworks:
        github: https://github.com/oscareduardolp6
        linkedin: https://www.linkedin.com/in/oscareduardolp6/
        # twitter: https://twitter.com
        instagram: https://www.instagram.com/oscar_lp6/
        # facebook: https://facebook.comg

params: 
  title: "Oscar López"
  favicon: "/favicon.ico"
  useBootstrapCDN: true 

  theme: 
    disableThemeToggle: false

  navbar: 
    menus: 
      disableAbout: true
      disableExperience: true
      disableEducation: true
      disableProjects: true
      disableAchievements: true
      disableContact: true