baseURL: http://example.org/
languageCode: es-mx
title: Oscar López 
theme: hugo-profile 

Paginate: 3
disqusShortname: oscarlp6

markup: 
  goldmark: 
    renderer: 
      unsafe: true 

Menus: 
  main: 
    - identifier: about
      name: Sobre mí
      title: Sobre mí 
      url: /#about
      wight: 1
    - identifier: experience
      name: Experiencia
      title: Experiencia
      url: /#experience
      wight: 1
    - identifier: education
      name: Educación
      title: Educación
      url: /#education
      wight: 1
    - identifier: achievements
      name: Logros
      title: Logros
      url: /#achievements
      wight: 1
    - identifier: contact
      name: Contacto
      title: Contacto
      url: /#contact
      wight: 1
    - identifier: projects
      name: Proyectos
      title: Proyectos
      url: /#projects
      wight: 1
    - identifier: blog 
      name: Blog
      title: Blog posts 
      url: /blogs
      weight: 1
      


params: 
  title: "Oscar López"
  description: Portafolio de Oscar López
  favicon: "/favicon.ico"
  useBootstrapCDN: true 

  theme: 
    disableThemeToggle: false

  navbar: 
    menus: 
      disableAbout: true
      disableExperience: true
      disableEducation: true
      disableProjects: true
      disableAchievements: true
      disableContact: true

  # navbar: 
    # brandLogo: "/logo.png"
  
  # Hero
  hero:
    enable: true
    intro: "Hola, soy"
    title: "Oscar López"
    subtitle: "Fullstack web developer" 
    # TODO: Mejorar la descripción 
    content: "Soy un apasionado de mi trabajo, me encanta estar aprendiendo cosas nuevas a diario, 
    interactuar con gente nueva y los retos que me ofrece la programación. En mi tiempo libre también soy *ilusionista* amateur"
    
    image: /profile.jpg
    button:
      enable: true
      name: "CV"
      url: "/docs/CV.pdf"
      download: true 
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/oscareduardolp6
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/oscareduardolp6/
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"
  
  # About
  about:
    enable: true
    title: "Sobre mi"
    image: "/images/me.jpg"
    content: |-
      Originario del Estado de México, viví en Monterrey y he pasado la mayoría de mi vida en León, Gto. 

      Tengo 22 años, y desde el 2020 me he dedicado al desarrollo de soluciones con enfoque al cliente, enfocandome, sobretodo, 
      a la parte web como **Fullstack**, creando y colaborando en soluciones tanto para Pymes como para grandes empresas. 

      Mi mayor interés en el desarrollo de cualquier pieza de software está en la arquitectura de esta, enfocandome a que sean piezas 
      mantenibles y escalables. 
      
      Estudié en el ITL (Instituto Técnologíco de León) ingeniería en sistemas computacionales. 

    skills:
      enable: true
      title: "Algunas de las Técnologías que manejo"
      items:
        # - "HTML" # Frontend 
        - "CSS / Sass" # Frontend 
        - "React (Con Typescript)" # Frontend
        - "Angular / AngularJS" # Frontend 
        - "TypeScript / JavaScript" # Backend / Frontend 
        - ".NET con C# & VB" # Backend 
        - "Node / Deno" # Backend 
        - "Python" # Backend 
        # - "Java (Spring)" # Backend 
        - "SQL / Transact-SQL" # Backend
        # - "Electron" # Desktop 

  # Experience
  experience:
    enable: true
    title: "Experiencia"
    # index: true
    items:
      - job: "Desarrollador de plataforma web"
        company: "Educafin"
        companyUrl: ""
        date: "Marzo 2020 - Diciembre 2021"
        info: 
          enable: false
        featuredLink:
          enable: false 
          name: "View the project"
          url: "https://example.com"
        content: "Parte de equipo de desarrollo de la plataforma 'SOS Inspira', pensada para que llevar el control del 
        programa de mentores y mentorados de la institución, construido en   `PHP vanilla`  con una base de datos   `MariaDb`.

        También estuve involucrado en el desarrollo inicial de la plataforma de 'JuventudesGTO', pensada más en la parte de investigación
        de la institución y su desarrollo inicial fue con `Code Igniter`
        "
      - job: "Desarrollador de proyectos de Software"
        company: "Proservicio"
        companyUrl: "https://www.serviacero.com/proservicio"
        date: "Octubre 2020 - Marzo 2022"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false 
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          Fui parte del equipo de desarrollo de nuevos proyectos, la empresa se enfoca en generar software tanto web, como módulos para 
          *ERP* personalizados para cada una de las especialidades del **[Grupo Serviacero](https://serviacero.com/)** 

          Participé en el desarrollo de integración del sistema con la emisión de *Carta Porte* para el SAT. 
      - job: "Desarrollador de .NET y Web"
        company: "IROX IT"
        companyUrl: "http://iroxit.com/"
        date: "Marzo 2022 -  Presente"
        info:
          enable: false
        featuredLink:
          enable: false 
          url: "https://example.com"
        content: |
          Actualmente trabajo en [IROX IT](http://iroxit.com/), una consultora de tecnología dónde he trabajado para proyectos con 
          cliente [HDI Seguros](https://www.hdi.com.mx/). 
          He formado parte de dos equipos de trabajo
          - **Asistencia a proveedores**: Enfocado a desarrollar módulos para el aplicativo interno para la gestión con proveedores, este desarrollado con `.NET` con *Winforms*
          - **Daños**: Enfocado en desarrollo de módulos y funcionalidad para la aplicación web interna para cotización y emisión de polizas, 
          desarrollado con `.NET` en un enfoque de servicios y `Angular` para el *frontend* 

  # Education
  education:
    enable: true
    title: Educación
    # index: true
    items:
      - title: "Ingeniería en sistemas computacionales"
        school:
          name: "Instituto Tecnológico de León"
          url: "https://leon.tecnm.mx/"
        date: "2017 - 2022"
        content: |-
          Actividades Extracurriculares: 
          - Tester de **Punto Azul** proyecto desarrollado por **[Aldo López](https://www.linkedin.com/in/aldo-l%C3%B3pez-868b10221/)** y **Andrés Sierra**
          - 1° Lugar dentro del instituto en el **Hackaton de la Universidad de Cundinamarca** 

      # - title: "Bachelor of Science in Computer Science"
      #   school:
      #     name: "Massachusetts Institute of Technology"
      #     url: "https://example.org"
      #   date: "2009 - 2013"
      #   GPA: "3.9 out of 5.0"
      #   content: |-
      #     I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
      #     - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
      #     - Face mask detection using a single convolutional neural network.
      #     Extracurricular Activities
      #       - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      #       - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      #   featuredLink:
      #     enable: true
      #     name: "My academic record"
      #     url: "https://example.com"
      # - title: "High School"
      #   school:
      #     name: "Thomas Jefferson High School for Science and Technology."
      #     url: "https://example.org"
      #   GPA: "4.2 out of 5.0"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"

  # Achievements
  achievements:
    title: "Logros"
    enable: true
    items:
      - title: Go desde cero 
        content: Certificado de terminación del Curso básico de Go 
        # url: https://ed.team/cursos/go
        url: /docs/Certifications/CertificadoGolang.png
      - title: Mis ejercicios de programación
        content: Ejercicios de programación en LeetCode
        url: https://leetcode.com/oscareduardolp6/

  # projects
  projects:
    title: "Proyectos"
    enable: true
    items:
      - title: "Manejador de Inventario para JM Muebleria"
        content: "Una herramienta hecha para ser el centro de control de la tienda, permitiendo tener la información de almacen centralizada 
        para ser consumida desde varias computadoras cliente, desarrollada con un servidor Deno en TypeScript y la UI con React & Electron" 

        image: /images/projects/Muebleria-1.png
        badges:
          - "Deno"
          - "Electron"
          - "React"
          - "Typescript"
        links:
          - icon: fab fa-facebook
            url: https://www.facebook.com/JMuebleria
          - icon: fab fa-github
            url: https://github.com/oscareduardolp6/muebleria
          - icon: fab fa-github
            url: https://github.com/oscareduardolp6/Share
          - icon: fab fa-github 
            url: https://github.com/oscareduardolp6/Owl_Sales_Point_Back 

      - title: "Entrenador de memoria"
        content: "Un proyecto para mejorar mi memoria, la idea es recordar cierto número de palabras en orden, para después repetirlas en
        en el mismo orden, el programa nos dirá si lo hemos hecho corrrectamente o si hemos fallado, para mejorar el resultado, se nos pregunta 
        si creemos que podemos recordar la palabra o si por no conocerla o su complejidad, queremos cambiarla."
        image: /images/projects/memory-trainer-1.png
        featured:
          name: Demo
          link: /projects/memory-trainer
        badges:
          - "React"
          - "CSS"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

  #Contact
  contact:
    title: Contacto
    enable: true
    content: No dudes en mandarme un correo para cualquier tema que queiras ver conmigo :) 
    email: oscareduardolp6@gmail.com
    btnName: Contactame

  footer:
    recentPosts: true
    recentPostTitle: Entradas Recientes
    socialNetworks:
      github: https://github.com/oscareduardolp6
      linkedin: https://www.linkedin.com/in/oscareduardolp6/
      # twitter: https://twitter.com
      instagram: https://www.instagram.com/oscar_lp6/
      # facebook: https://facebook.comg
      

